---
# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    meta: "{{ item.value.meta.0 }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    key_name: "{{ item.value.key_name }}"
    wait: yes
    nics:
    - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -s http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      curl -s -o /etc/yum.repos.d/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  with_dict: "{{ osp_servers }}"

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 180
  with_dict: "{{ osp_servers }}"
  register: instancefloatingip
